export const ARMAZENAR_INVESTIDOR = 'GUARDAR_INVESTIDOR';
export const SETAR_INVESTIDOR_ATUAL = 'SETAR_INVESTIDOR_ATUAL';

export const INVESTIDOR_LOCALIZADO = 'INVESTIDOR_LOCALIZADO';

export const BUSCAR_INVESTIDOR_LOGADO = 'BUSCAR_INVESTIDOR_LOGADO';
export const BUSCAR_INVESTIDORES = 'BUSCAR_INVESTIDORES';
export const BUSCAR_INVESTIDOR_POR_ID = 'BUSCAR_INVESTIDOR_POR_ID';
export const ATUALIZAR_INVESTIDOR = 'ATUALIZAR_INVESTIDOR'
export const EXCLUIR_INVESTIDOR = 'EXCLUIR_INVESTIDOR';
export const INCLUIR_INVESTIDOR = 'INCLUIR_INVESTIDOR';